### ISSUE TITLE
https does not work

### ISSUE THREAD

**Issue by emillon** [ocaml/dune-www#3]
At the moment, https://dune.build presents the wrong certificate.

According to [this page](https://help.github.com/articles/troubleshooting-custom-domains/#https-errors), it might be because it is using the wrong IP addresses. Depending on how the DNS record is configured, we might have to update the `A` records [like this](https://help.github.com/articles/setting-up-an-apex-domain/#configuring-a-records-with-your-dns-provider).

That might not be enough, since simulating this does not work:

```
% curl https://dune.build --resolve dune.build:443:192.30.252.154 
curl: (51) SSL: no alternative certificate subject name matches target host name 'dune.build'
```

**Comment by avsm** [comment]
I've updated the `A` records on `dune.build` DNS to point to:

```
@ 1800 IN A 185.199.108.153
@ 1800 IN A 185.199.109.153
@ 1800 IN A 185.199.110.153
@ 1800 IN A 185.199.111.153
```

once it propagates, let's see if that fixes the certificate.

**Comment by emillon** [comment]
Doesn't seem to be enough :/

According to the docs:

> After updating any A record IP addresses, you must remove and re-add your custom domain to the repository you’re using to publish your Pages site to trigger the process of enabling HTTPS.

I guess that it will re-trigger a job that reads `CNAME` in the repo and request a LE cert. Can you try that when it's convenient for you? Thanks!

**Comment by mc10** [comment]
This no longer seems like it's an issue for me; can you confirm whether you still have this issue?

@ maintainers: I would recommend redirecting the HTTP site to the HTTPS site.

**Comment by emillon** [comment]
Yep that works fine now! According to [the CT logs](https://crt.sh/?q=dune.build), this was enabled in august.

I agree about enforcing HTTPS, [according to the docs](https://help.github.com/articles/securing-your-github-pages-site-with-https/) it's just a checkbox to tick :)

**Comment by emillon** [comment]
I just ticked the box and this now redirects to https.
